spring.application.name=sonidosweb
server.port=${PORT:8080}

# Database PostgreSQL (Railway)
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8
